version: "3.1"

services:
  frontend:
    container_name: goreact-frontend
    build: 
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
  
  backend:
    container_name: goreact-backend
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app 
