version: "3.1"

services:
  frontend:
    container_name: goreact-frontend
    build: 
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
  
  backend:
    container_name: goreact-backend
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app 

  mysql:
    image: mysql:latest
    container_name: goreact-mysql
    restart: on-failure
    # cpus: "1.0"
    # mem_limit: "1g"
    environment:
      MYSQL_HOST: "localhost"
      MYSQL_DATABASE: "gofiber_react_app"
      MYSQL_USER: "gofiber_react"
      MYSQL_PASSWORD: "VyLg8R6BzS5KVwMcDK"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "6MpU5tQaVXvBFqSLDFN25v9zzgRbcvDK"
    ports:
      - "53309:3309"
    volumes:
      - goreact-mysql_data:/var/lib/mysql
  
volumes:
  goreact-mysql_data: